In [19]:
import pandas as pd
df = pd.read_csv('products.csv', encoding='UTF-8')
df_dummies = pd.get_dummies(df, columns=['kategorie']).astype(int)

#ergebnis anzeigen
print('\nOne-Hot-Kodierung mit pandas get_dummies: ')
print(df_dummies)


One-Hot-Kodierung mit pandas get_dummies: 
    kategorie_Bücher  kategorie_Elektronik  kategorie_Kleidung
0                  0                     1                   0
1                  0                     0                   1
2                  1                     0                   0
3                  0                     1                   0
4                  0                     1                   0
5                  1                     0                   0
6                  0                     0                   1
7                  1                     0                   0
8                  0                     1                   0
9                  0                     0                   1
10                 1                     0                   0
11                 0                     1                   0
12                 1                     0                   0
13                 0                     1                   0
14         

## Converting Text to Featrures II

In [20]:
#pip install scikit-learn


[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


#### 4.2.1 Textklassifizierung am Beispiel Spam/Ham 

In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [22]:
from sklearn.feature_extraction.text import CountVectorizer 
text = [     
    "NLP unlocks insights, NLP evolving.",     
    "ML learns patterns; ML applications abound.",     
    "NLP preprocessing crucial for NLP understanding." 
] 

vectorizer = CountVectorizer() 

# Erstellt das Vokabular aus den Textdaten 
X=vectorizer.fit(text) 

print("Vokabular", vectorizer.vocabulary_)

# Features ausgeben 
print("Vokabular", vectorizer.vocabulary_) 

# Text basierend auf Vokabular vektorisieren. Ergebnis ist BoW 
X=vectorizer.transform(text) 

print("Bag of Words\n", X.toarray()) 

Vokabular {'nlp': 8, 'unlocks': 12, 'insights': 5, 'evolving': 3, 'ml': 7, 'learns': 6, 'patterns': 9, 'applications': 1, 'abound': 0, 'preprocessing': 10, 'crucial': 2, 'for': 4, 'understanding': 11}
Vokabular {'nlp': 8, 'unlocks': 12, 'insights': 5, 'evolving': 3, 'ml': 7, 'learns': 6, 'patterns': 9, 'applications': 1, 'abound': 0, 'preprocessing': 10, 'crucial': 2, 'for': 4, 'understanding': 11}
Bag of Words
 [[0 0 0 1 0 1 0 0 2 0 0 0 1]
 [1 1 0 0 0 0 1 2 0 1 0 0 0]
 [0 0 1 0 1 0 0 0 2 0 1 1 0]]


In [23]:
spam = pd.read_csv("spam.csv", encoding='latin1')
spam = spam[["v1","v2"]]
spam.columns = ['target', 'message']
spam

target                                            message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham              Will Ì_ b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

#### Step 2

https://scikit-learn.org/1.5/modules/generated/sklearn.model_selection.train_test_split.html

In [24]:
X = spam['message']
y = spam['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) # 0.3 = 30%

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X_train shape: (3900,)
y_train shape: (3900,)
X_test shape: (1672,)
y_test shape: (1672,)


#### Step 3

https://scikit-learn.org/1.5/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder

In [26]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.3, random_state=42)
vectorizer = CountVectorizer()
vectorizer.fit(X)
print(f"CountVectorizer: {len(vectorizer.vocabulary_)} Features")

X_train_vectorized = vectorizer.transform(X_train)
X_valid_vectorized = vectorizer.transform(X_valid)

print(f"X_train_vectorized {X_train_vectorized.shape} and X_valid_vectorized {X_valid_vectorized.shape}")

label_encoder = LabelEncoder()
y_train_num = label_encoder.fit_transform(y_train)
y_valid_num = label_encoder.transform(y_valid)

print("y_train_num:", y_train_num[:5])
print("y_valid_num:", y_valid_num[:5])

CountVectorizer: 8672 Features
X_train_vectorized (3900, 8672) and X_valid_vectorized (1672, 8672)
y_train_num: [1 0 0 0 0]
y_valid_num: [0 0 1 0 1]


#### Step 4

Training des Naive Bayes Classifiers: 

In [27]:
from sklearn import naive_bayes, metrics

In [28]:
clf = naive_bayes.MultinomialNB(alpha=0.2) 
clf.fit(X_train_vectorized, y_train_num) 
predictions = clf.predict(X_valid_vectorized) 
metrics.accuracy_score(predictions, y_valid_num) 

0.9796650717703349

#### Step 5

In [33]:
msg=vectorizer.transform(["Congratulations! You've won a complimentary entry to the exclusive VIP event. Claim your free pass for the grand finale on June 15, 2023, by texting VIP to 44882. Standard text messaging rates apply. For more details, call 1-800-123-4567. Don't miss out on this incredible opportunity! Terms and conditions apply. Must be 18 or older to participate."]) 
clf.predict(msg) 

array([1])